# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-30 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATRitems', '0004_item_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='functionary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
