# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-30 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATRitems', '0005_item_functionary'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='functionary',
            field=models.CharField(max_length=200),
        ),
    ]
