# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 01:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ATRitems', '0011_auto_20180405_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='functionaries',
        ),
        migrations.AddField(
            model_name='item',
            name='year_no',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='item',
            name='functionary',
        ),
        migrations.AddField(
            model_name='item',
            name='functionary',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
