# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 21:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ATRitems', '0006_auto_20180330_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='functionaries',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
